// Code Generated by Sidekick is for learning and experimentation purposes only.
(() => {
  const el = (id) => document.getElementById(id);

  const fileEl = el("file");
  const statusEl = el("status");

  const btnGenerate = el("btnGenerate");
  const btnCopy = el("btnCopy");
  const btnClear = el("btnClear");

  const analysisEditor = el("analysisEditor");
  const summaryEditor = el("summaryEditor");

  // NEW: detail inputs
  const focalNameEl = el("focalName");
  const cityEl = el("city");
  const stateEl = el("state");
  const occupationEl = el("occupation");
  const escalationTypeEl = el("escalationType");
  const summaryModeEl = el("summaryMode");

  let rows = [];
  let fileName = "";

  function setStatus(msg, kind = "") {
    statusEl.textContent = msg || "";
    statusEl.className = "status" + (kind ? ` ${kind}` : "");
  }

  function normalize(s) {
    return String(s ?? "")
      .trim()
      .toLowerCase()
      .replace(/\s+/g, " ")
      .replace(/[^a-z0-9 ]/g, "");
  }

  // NEW: find a sheet named "Transactions" (case/space tolerant)
  function findSheetByName(wb, wantedName) {
    const wanted = normalize(wantedName);
    return (wb.SheetNames || []).find((n) => normalize(n) === wanted) || "";
  }

  function findCol(headers, candidates) {
    const normToOrig = new Map(headers.map((h) => [normalize(h), h]));
    for (const c of candidates) {
      const hit = normToOrig.get(normalize(c));
      if (hit) return hit;
    }
    const normHeaders = headers.map((h) => ({ h, n: normalize(h) }));
    for (const c of candidates) {
      const cn = normalize(c);
      const hit = normHeaders.find((x) => x.n.includes(cn) || cn.includes(x.n));
      if (hit) return hit.h;
    }
    return "";
  }

  function parseAmount(v) {
    if (v == null || v === "") return NaN;
    if (typeof v === "number") return v;

    const cleaned = String(v)
      .trim()
      .replace(/[^0-9.,\-()]/g, "");
    const neg = /^\(.*\)$/.test(cleaned);
    const unwrapped = cleaned.replace(/[()]/g, "");

    const parts = unwrapped.split(".");
    let numStr = unwrapped;
    if (parts.length > 2) {
      const last = parts.pop();
      numStr = parts.join("") + "." + last;
    }
    numStr = numStr.replace(/,/g, "");
    const n = Number(numStr);
    if (!Number.isFinite(n)) return NaN;
    return neg ? -n : n;
  }

  function parseDate(v) {
    if (v == null || v === "") return null;
    if (v instanceof Date && !isNaN(v)) return v;
    if (typeof v === "number") {
      const epoch = new Date(Date.UTC(1899, 11, 30));
      const d = new Date(epoch.getTime() + v * 86400000);
      return isNaN(d) ? null : d;
    }
    const d = new Date(String(v));
    return isNaN(d) ? null : d;
  }

  function fmtMoney(n) {
    if (!Number.isFinite(n)) return "N/A";
    const sign = n < 0 ? "-" : "";
    const abs = Math.abs(n);
    return `${sign}${abs.toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;
  }

  function fmtDate(d) {
    return d instanceof Date && !isNaN(d)
      ? d.toISOString().slice(0, 10)
      : "N/A";
  }

  // FIXED: escape < and > correctly (prevents HTML injection)
  function esc(s) {
    return String(s ?? "")
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll('"', "&quot;")
      .replaceAll("'", "&#39;");
  }

  function sanitizeBasicHtml(html) {
    const allowed = new Set([
      "B",
      "STRONG",
      "I",
      "EM",
      "U",
      "BR",
      "DIV",
      "P",
      "UL",
      "OL",
      "LI",
      "SPAN",
    ]);
    const tpl = document.createElement("template");
    tpl.innerHTML = String(html || "");

    const walk = (node) => {
      const children = Array.from(node.childNodes);
      for (const ch of children) {
        if (ch.nodeType === Node.ELEMENT_NODE) {
          const tag = ch.tagName.toUpperCase();
          if (!allowed.has(tag)) {
            const frag = document.createDocumentFragment();
            while (ch.firstChild) frag.appendChild(ch.firstChild);
            ch.replaceWith(frag);
          } else {
            for (const attr of Array.from(ch.attributes))
              ch.removeAttribute(attr.name);
            walk(ch);
          }
        } else if (ch.nodeType === Node.COMMENT_NODE) {
          ch.remove();
        }
      }
    };

    walk(tpl.content);
    return tpl.innerHTML;
  }

  function buildSummaryHtml() {
    if (!rows.length) throw new Error("No transactions loaded.");

    const focalName = (focalNameEl?.value || "").trim() || "N/A";
    const city = (cityEl?.value || "").trim() || "N/A";
    const state = (stateEl?.value || "").trim() || "N/A";
    const occupation = (occupationEl?.value || "").trim() || "N/A";
    const escalationType = escalationTypeEl?.value || "non_escalation";
    const summaryMode = summaryModeEl?.value || "standard";

    const headers = Object.keys(rows[0] || {});
    const amtCol = findCol(headers, [
      "amount",
      "amt",
      "value",
      "transaction amount",
      "debit",
      "credit",
    ]);

    if (!amtCol) throw new Error('Could not detect an "amount" column.');

    const amounts = rows
      .map((r) => parseAmount(r[amtCol]))
      .filter((n) => Number.isFinite(n));

    const credit = amounts.filter((n) => n > 0).reduce((a, n) => a + n, 0);
    const debit = Math.abs(
      amounts.filter((n) => n < 0).reduce((a, n) => a + n, 0),
    );
    const creditText = `$${fmtMoney(credit)}`;
    const debitText = `$${fmtMoney(debit)}`;

    let paragraph = "";
    if (escalationType === "escalation" && summaryMode === "standard") {
      paragraph = `Escalation summary: The focal entity is "${focalName}" located in ${city}, ${state}, with occupation "${occupation}". Total credits are ${creditText} and total debits are ${debitText}.`;
    } else if (
      escalationType === "escalation" &&
      summaryMode === "simplified"
    ) {
      paragraph = `Escalation: "${focalName}" (${city}, ${state}; "${occupation}") — Credits ${creditText}; Debits ${debitText}.`;
    } else if (
      escalationType === "non_escalation" &&
      summaryMode === "standard"
    ) {
      paragraph = `Summary: The focal entity is "${focalName}" located in ${city}, ${state}, with occupation "${occupation}". Total credits are ${creditText} and total debits are ${debitText}.`;
    } else if (
      escalationType === "non_escalation" &&
      summaryMode === "simplified"
    ) {
      paragraph = `Non-escalation: "${focalName}" (${city}, ${state}; "${occupation}") — Credits ${creditText}; Debits ${debitText}.`;
    } else {
      alert("Please check all the input fields are selected correctly.");
      paragraph = "";
    }

    return `
    <div>
      <p>${esc(paragraph)}</p>
    </div>
  `.trim();
  }

  async function copySummary() {
    const html = summaryEditor.innerHTML;
    const text = summaryEditor.innerText;
    if (!text.trim()) return;

    try {
      if (navigator.clipboard && window.ClipboardItem) {
        await navigator.clipboard.write([
          new ClipboardItem({
            "text/html": new Blob([html], { type: "text/html" }),
            "text/plain": new Blob([text], { type: "text/plain" }),
          }),
        ]);
      } else {
        await navigator.clipboard.writeText(text);
      }
      setStatus("Copied.", "ok");
    } catch {
      setStatus("Copy blocked—select and copy manually.", "bad");
    }
  }

  function clearAll() {
    rows = [];
    fileName = "";
    fileEl.value = "";

    analysisEditor.innerHTML = "";
    summaryEditor.innerHTML = "";

    btnGenerate.disabled = true;
    btnCopy.disabled = true;
    btnClear.disabled = true;

    setStatus("", "");
  }

  document.addEventListener("click", (e) => {
    const btn = e.target.closest("[data-cmd], [data-action]");
    if (!btn) return;

    const targetId = btn.getAttribute("data-target");
    const target = targetId ? document.getElementById(targetId) : null;
    if (!target) return;

    target.focus();

    const cmd = btn.getAttribute("data-cmd");
    const action = btn.getAttribute("data-action");

    if (cmd) document.execCommand(cmd, false, null);
    if (action === "clearFormat") {
      document.execCommand("removeFormat", false, null);
      document.execCommand("unlink", false, null);
    }
  });

  summaryEditor.addEventListener("input", () => {
    btnCopy.disabled = !summaryEditor.textContent.trim();
  });

  // UPDATED: load the "Transactions" sheet specifically
  fileEl.addEventListener("change", async () => {
    setStatus("", "");
    const f = fileEl.files?.[0];
    if (!f) return;

    try {
      if (!window.XLSX)
        throw new Error("Missing XLSX library (xlsx.full.min.js).");

      fileName = f.name;
      const buf = await f.arrayBuffer();
      const wb = XLSX.read(buf, { type: "array", cellDates: true });

      const sheetName = findSheetByName(wb, "Transactions");
      if (!sheetName) {
        const available = (wb.SheetNames || []).join(", ") || "(none)";
        throw new Error(
          `Sheet "Transactions" not found. Available: ${available}`,
        );
      }

      const ws = wb.Sheets[sheetName];
      const json = XLSX.utils.sheet_to_json(ws, { defval: "" });
      if (!json.length)
        throw new Error('No rows found in "Transactions" sheet.');

      rows = json;

      btnGenerate.disabled = false;
      btnClear.disabled = false;

      setStatus(`Loaded: ${f.name} (Sheet: ${sheetName})`, "ok");
    } catch (err) {
      clearAll();
      setStatus(err?.message || "Failed to load file.", "bad");
    }
  });

  btnGenerate.addEventListener("click", () => {
    try {
      const html = buildSummaryHtml();
      summaryEditor.innerHTML = html;
      btnCopy.disabled = !summaryEditor.textContent.trim();
      setStatus("Generated. Edit the summary as needed.", "ok");
    } catch (err) {
      setStatus(err?.message || "Failed to generate summary.", "bad");
    }
  });

  btnCopy.addEventListener("click", copySummary);
  btnClear.addEventListener("click", clearAll);

  clearAll();
})();
