// Code Generated by Sidekick is for learning and experimentation purposes only.
(() => {
  const el = (id) => document.getElementById(id);

  const fileEl = el("file");
  const statusEl = el("status");

  const btnGenerate = el("btnGenerate");
  const btnCopy = el("btnCopy");
  const btnClear = el("btnClear");

  const analysisEditor = el("analysisEditor");
  const summaryEditor = el("summaryEditor");
  const focalTypeEl = document.getElementById("focalType");
  const individualFormEl = document.getElementById("focal-individual-form");
  const entityFormEl = document.getElementById("focal-entity-form");
  let rows = [];
  let fileName = "";

  function setStatus(msg, kind = "") {
    statusEl.textContent = msg || "";
    statusEl.className = "status" + (kind ? ` ${kind}` : "");
  }

  function normalize(s) {
    return String(s ?? "")
      .trim()
      .toLowerCase()
      .replace(/\s+/g, " ")
      .replace(/[^a-z0-9 ]/g, "");
  }

  // NEW: find a sheet named "Transactions" (case/space tolerant)
  function findSheetByName(wb, wantedName) {
    const wanted = normalize(wantedName);
    return (wb.SheetNames || []).find((n) => normalize(n) === wanted) || "";
  }
  function setFocalFormVisibility() {
    const type = focalTypeEl?.value || "individual";
    const isIndividual = type === "individual";

    individualFormEl.classList.toggle("hidden", !isIndividual);
    entityFormEl.classList.toggle("hidden", isIndividual);
  }

  focalTypeEl?.addEventListener("change", setFocalFormVisibility);
  setFocalFormVisibility();

  // Optional helper to read active form values with N/A fallback
  function valOrNA(id) {
    const v = (document.getElementById(id)?.value || "").trim();
    return v || "N/A";
  }
  function getFocalDetails() {
    const type = focalTypeEl?.value || "individual";

    if (type === "individual") {
      return {
        type,
        focalName: valOrNA("ind_focalName"),
        dob: valOrNA("ind_dob"),
        city: valOrNA("ind_city"),
        state: valOrNA("ind_state"),
        occupation: valOrNA("ind_occupation"),
        employer: valOrNA("ind_employer"),
        reason: valOrNA("ind_reason"),
      };
    }

    if (type === "entity") {
      return {
        type,
        focalName: valOrNA("ent_focalName"),
        incorpDate: valOrNA("ent_incorpDate"),
        city: valOrNA("ent_city"),
        state: valOrNA("ent_state"),
        relationshipStart: valOrNA("ent_relationshipStart"),
        natureBusiness: valOrNA("ent_natureBusiness"),
        naics: valOrNA("ent_naics"),
        addlInfo: valOrNA("ent_addlInfo"),
        relatedParty: valOrNA("ent_relatedParty"),
        reason: valOrNA("ent_reason"),
      };
    }

    alert("Please select a valid focal entity type.");
    return null;
  }
  function findCol(headers, candidates) {
    const normToOrig = new Map(headers.map((h) => [normalize(h), h]));
    for (const c of candidates) {
      const hit = normToOrig.get(normalize(c));
      if (hit) return hit;
    }
    const normHeaders = headers.map((h) => ({ h, n: normalize(h) }));
    for (const c of candidates) {
      const cn = normalize(c);
      const hit = normHeaders.find((x) => x.n.includes(cn) || cn.includes(x.n));
      if (hit) return hit.h;
    }
    return "";
  }
  wireRfiStatusFields();

  function parseAmount(v) {
    if (v == null || v === "") return NaN;
    if (typeof v === "number") return v;

    const cleaned = String(v)
      .trim()
      .replace(/[^0-9.,\-()]/g, "");
    const neg = /^\(.*\)$/.test(cleaned);
    const unwrapped = cleaned.replace(/[()]/g, "");

    const parts = unwrapped.split(".");
    let numStr = unwrapped;
    if (parts.length > 2) {
      const last = parts.pop();
      numStr = parts.join("") + "." + last;
    }
    numStr = numStr.replace(/,/g, "");
    const n = Number(numStr);
    if (!Number.isFinite(n)) return NaN;
    return neg ? -n : n;
  }

  function fmtMoney(n) {
    if (!Number.isFinite(n)) return "N/A";
    const sign = n < 0 ? "-" : "";
    const abs = Math.abs(n);
    return `${sign}${abs.toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;
  }

  function fmtDate(d) {
    return d instanceof Date && !isNaN(d)
      ? d.toISOString().slice(0, 10)
      : "N/A";
  }

  // FIXED: escape < and > correctly (prevents HTML injection)
  function esc(s) {
    return String(s ?? "")
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll('"', "&quot;")
      .replaceAll("'", "&#39;");
  }

  function sanitizeBasicHtml(html) {
    const allowed = new Set([
      "B",
      "STRONG",
      "I",
      "EM",
      "U",
      "BR",
      "DIV",
      "P",
      "UL",
      "OL",
      "LI",
      "SPAN",
    ]);
    const tpl = document.createElement("template");
    tpl.innerHTML = String(html || "");

    const walk = (node) => {
      const children = Array.from(node.childNodes);
      for (const ch of children) {
        if (ch.nodeType === Node.ELEMENT_NODE) {
          const tag = ch.tagName.toUpperCase();
          if (!allowed.has(tag)) {
            const frag = document.createDocumentFragment();
            while (ch.firstChild) frag.appendChild(ch.firstChild);
            ch.replaceWith(frag);
          } else {
            for (const attr of Array.from(ch.attributes))
              ch.removeAttribute(attr.name);
            walk(ch);
          }
        } else if (ch.nodeType === Node.COMMENT_NODE) {
          ch.remove();
        }
      }
    };

    walk(tpl.content);
    return tpl.innerHTML;
  }
  function buildRfiSummary(focalEntityName) {
    const fe = (focalEntityName || "").trim() || "N/A";

    const status =
      document.getElementById("rfi_status")?.value || "no_prior_rfi_flag";
    const valOrNA = (id) =>
      (document.getElementById(id)?.value || "").trim() || "N/A";

    if (status === "no_prior_rfi_flag") {
      return `There are no prior RFIs identified for ${fe}.`;
    }

    if (status === "prior_rfi_flag_present") {
      const count = valOrNA("rfi_count");
      const submitted = valOrNA("rfi_submitted_date");
      const questions = valOrNA("rfi_questions_summary");
      const responseDate = valOrNA("rfi_questions_received_date");
      const responseDetails = valOrNA("rfi_response_detail");

      return `A total of ${count} prior RFIs were identified for ${fe}. An RFI was submitted by TD on ${submitted} to inquire about ${questions}. A response was received on ${responseDate}. The customer/branch stated: ${responseDetails}.`;
    }

    if (status === "lookback_submitted_no_response") {
      const submitted = valOrNA("rfi_lookback_submitted_date");
      const purpose = valOrNA("rfi_lookback_purpose");
      const today = valOrNA("rfi_todays_date");

      return `During the Lookback an RFI was submitted to TD on ${submitted} regarding ${purpose}. As of ${today}, no response has been received.`;
    }

    if (status === "lookback_submitted_response_received") {
      const submitted = valOrNA("rfi_lookback_resp_submitted_date");
      const purpose = valOrNA("rfi_lookback_resp_purpose");
      const received = valOrNA("rfi_lookback_resp_received_date");
      const summary = valOrNA("rfi_response_summary");

      return `During the Lookback, an RFI was submitted to TD on ${submitted} regarding ${purpose}. A response was received on ${received}, stating: ${summary}.`;
    }

    return "";
  }
  function wireCustomerStatusToggle() {
    const statusEl = document.getElementById("ind_customerStatus");
    const inactiveWrap = document.getElementById("ind_inactive_fields");
    const endDateEl = document.getElementById("ind_endDate");
    const reasonEl = document.getElementById("ind_reason");
    if (!statusEl || !inactiveWrap) return;

    const apply = () => {
      const isInactive = statusEl.value === "inactive";
      inactiveWrap.style.display = isInactive ? "" : "none";

      // Optional: clear values when hidden
      if (!isInactive) {
        if (endDateEl) endDateEl.value = "";
        if (reasonEl) reasonEl.value = "";
      }
    };

    statusEl.addEventListener("change", apply);
    apply(); // run once on load
  }
  function buildCounterpartySummary() {
    console.log("e");

    const count =
      Number.parseInt(
        document.getElementById("counterparty_count")?.value,
        10,
      ) || 0;
    const lines = [];

    for (let i = 1; i <= count; i++) {
      const name = document.getElementById(`cp_${i}_name`)?.value?.trim() || "";
      const reason =
        document.getElementById(`cp_${i}_reason`)?.value?.trim() || "";
      const addl = document.getElementById(`cp_${i}_addl`)?.value?.trim() || "";

      if (!name && !reason && !addl) continue;

      let s = `Counterparty ${name || `#${i}`} has been sampled`;
      if (reason) s += ` due to ${reason}`;
      s += `.`;
      if (addl) s += ` “${addl}”.`;

      lines.push(s);
    }

    return lines;
  }
  function buildSummaryHtml() {
    if (!rows.length) throw new Error("No transactions loaded.");

    const valOrNA = (id) =>
      (document.getElementById(id)?.value || "").trim() || "N/A";
    const valTrim = (id) => (document.getElementById(id)?.value || "").trim();

    // Detect amount column and compute credits/debits
    const headers = Object.keys(rows[0] || {});
    const amtCol = findCol(headers, [
      "amount",
      "amt",
      "value",
      "transaction amount",
      "debit",
      "credit",
    ]);
    if (!amtCol) throw new Error('Could not detect an "amount" column.');

    const amounts = rows
      .map((r) => parseAmount(r[amtCol]))
      .filter((n) => Number.isFinite(n));
    const credit = amounts.filter((n) => n > 0).reduce((a, n) => a + n, 0);
    const debit = Math.abs(
      amounts.filter((n) => n < 0).reduce((a, n) => a + n, 0),
    );
    const creditText = `$${fmtMoney(credit)}`;
    const debitText = `$${fmtMoney(debit)}`;

    const focalType =
      document.getElementById("focalType")?.value || "individual";

    let focalentitysummary = "";

    if (focalType === "individual") {
      const name = valOrNA("ind_focalName");
      const dobRaw = valTrim("ind_dob");
      const yob =
        dobRaw && !Number.isNaN(new Date(dobRaw).getTime())
          ? String(new Date(dobRaw).getFullYear())
          : "N/A";

      const city = valOrNA("ind_city");
      const state = valOrNA("ind_state");
      const occupation = valOrNA("ind_occupation");
      const employer = valOrNA("ind_employer");
      const relStart = valOrNA("ind_relationshipStart");

      const addlInfo = valTrim("ind_addlInfo");
      const addlInfoClause = addlInfo ? ` ${addlInfo}` : "";

      const customerStatusEl = document.getElementById("ind_customerStatus");
      const endDateRaw = valTrim("ind_endDate");
      const reasonRaw = valTrim("ind_reason");

      const customerStatus =
        (customerStatusEl && customerStatusEl.value) ||
        (endDateRaw || reasonRaw ? "inactive" : "active");

      let statusSentence = "";
      if (customerStatus === "inactive") {
        const endDate = valOrNA("ind_endDate");
        const reason = valOrNA("ind_reason");

        if (endDate === "N/A" || reason === "N/A") {
          alert('Please fill "No longer customer as of" date and reason.');
        }
        statusSentence = `${name} is no longer a TD customer as of ${endDate} because ${reason}.`;
      } else {
        statusSentence = `${name}'s accounts remain active.`;
      }

      focalentitysummary =
        ` ${name}, born in ${yob}, is located in ${city}, ${state} and has been a TD Bank customer since ${relStart}. ` +
        `${name} is a ${occupation} for ${employer}, per internal records${addlInfoClause}. ` +
        `(${statusSentence}) ` +
        `Total credits are ${creditText} and total debits are ${debitText}.`;
    } else if (focalType === "entity") {
      const name = valOrNA("ent_focalName");
      const incorp = valOrNA("ent_incorpDate");
      const city = valOrNA("ent_city");
      const state = valOrNA("ent_state");
      const relStart = valOrNA("ent_relationshipStart");
      const nature = valOrNA("ent_natureBusiness");
      const naics = valOrNA("ent_naics");
      const relatedParty = valOrNA("ent_relatedParty");

      const addlInfo = valTrim("ent_addlInfo");
      const addlInfoClause = addlInfo
        ? ` Additional information: ${addlInfo}.`
        : "";

      const customerStatusEl = document.getElementById("ent_customerStatus");
      const endDateRaw = valTrim("ent_endDate");
      const reasonRaw = valTrim("ent_reason");

      const customerStatus =
        (customerStatusEl && customerStatusEl.value) ||
        (endDateRaw || reasonRaw ? "inactive" : "active");

      let statusSentence = "";
      if (customerStatus === "inactive") {
        const endDate = valOrNA("ent_endDate");
        const reason = valOrNA("ent_reason");

        if (endDate === "N/A" || reason === "N/A") {
          alert('Please fill "No longer customer as of" date and reason.');
        }
        statusSentence = `${name} is no longer a TD customer as of ${endDate} because ${reason}.`;
      } else {
        statusSentence = `${name}'s accounts remain active.`;
      }

      focalentitysummary =
        `${name}, incorporated on ${incorp}, is located in ${city}, ${state} and has been a TD Bank customer since ${relStart}. ` +
        `${name}'s nature of business is ${nature} (NAICS: ${naics}). Related party: ${relatedParty}.` +
        `${addlInfoClause} ` +
        `(${statusSentence}) ` +
        `Total credits are ${creditText} and total debits are ${debitText}.`;
    } else {
      alert("Please check all the input fields are selected correctly.");
      focalentitysummary = "";
    }
    const name = valOrNA("ind_focalName");
    let Rfisummary = buildRfiSummary(name);
    let counterpartyLines = buildCounterpartySummary();
    return `
    <div>
      <p>${esc(focalentitysummary)}</p>
      <p>${esc(Rfisummary)}</p>
       ${counterpartyLines.map((l) => `<p>${esc(l)}</p>`).join("")}
    </div>
  `.trim();
  }

  function wireRfiStatusFields() {
    const statusEl = document.getElementById("rfi_status");
    const priorEl = document.getElementById("rfi_fields_prior");
    const noRespEl = document.getElementById("rfi_fields_lookback_noresp");
    const respEl = document.getElementById("rfi_fields_lookback_resp");
    const todaysEl = document.getElementById("rfi_todays_date");

    if (!statusEl || !priorEl || !noRespEl || !respEl) return;

    const setTodayIfEmpty = () => {
      if (!todaysEl) return;
      if (!todaysEl.value)
        todaysEl.value = new Date().toISOString().slice(0, 10);
    };

    const sync = () => {
      const v = statusEl.value;

      priorEl.classList.toggle("hidden", v !== "prior_rfi_flag_present");
      noRespEl.classList.toggle(
        "hidden",
        v !== "lookback_submitted_no_response",
      );
      respEl.classList.toggle(
        "hidden",
        v !== "lookback_submitted_response_received",
      );

      if (v === "lookback_submitted_no_response") setTodayIfEmpty();

      console.log("RFI status:", v);
    };

    statusEl.addEventListener("change", sync);
    sync();
  }
  function wireCounterpartyAddButton() {
    const countEl = document.getElementById("counterparty_count");
    const btnEl = document.getElementById("counterparty_add_btn");
    const wrapEl = document.getElementById("counterparty_fields");
    if (!countEl || !btnEl || !wrapEl) return;

    const build = () => {
      wrapEl.innerHTML = "";

      const count = Math.max(
        0,
        Math.min(100, Number.parseInt(countEl.value, 10) || 0),
      ); // cap at 100
      for (let i = 1; i <= count; i++) {
        const section = document.createElement("div");
        section.className = "card";
        section.style.marginTop = "10px";
        section.style.padding = "10px";

        section.innerHTML = `
        <div class="row"><div><label class="label">Counterparty ${i}</label></div></div>

        <label class="label" for="cp_${i}_name">Counterparty name</label>
        <input id="cp_${i}_name" type="text" placeholder="Counterparty name" />

        <label class="label" for="cp_${i}_reason">Reason for sampled</label>
        <input id="cp_${i}_reason" type="text" placeholder="Reason for sampled" />

        <label class="label" for="cp_${i}_addl">Additional information</label>
        <input id="cp_${i}_addl" type="text" placeholder="Additional information" />
      `;
        wrapEl.appendChild(section);
      }
    };

    btnEl.addEventListener("click", build);

    // Optional: press Enter in the number input to trigger Add
    countEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") build();
    });
  }
  wireCounterpartyAddButton();
  wireCustomerStatusToggle();
  async function copySummary() {
    const html = summaryEditor.innerHTML;
    const text = summaryEditor.innerText;
    if (!text.trim()) return;

    try {
      if (navigator.clipboard && window.ClipboardItem) {
        await navigator.clipboard.write([
          new ClipboardItem({
            "text/html": new Blob([html], { type: "text/html" }),
            "text/plain": new Blob([text], { type: "text/plain" }),
          }),
        ]);
      } else {
        await navigator.clipboard.writeText(text);
      }
      setStatus("Copied.", "ok");
    } catch {
      setStatus("Copy blocked—select and copy manually.", "bad");
    }
  }

  function clearAll() {
    rows = [];
    fileName = "";
    fileEl.value = "";

    summaryEditor.innerHTML = "";

    btnGenerate.disabled = true;
    btnCopy.disabled = true;
    btnClear.disabled = true;

    setStatus("", "");
  }

  document.addEventListener("click", (e) => {
    const btn = e.target.closest("[data-cmd], [data-action]");
    if (!btn) return;

    const targetId = btn.getAttribute("data-target");
    const target = targetId ? document.getElementById(targetId) : null;
    if (!target) return;

    target.focus();

    const cmd = btn.getAttribute("data-cmd");
    const action = btn.getAttribute("data-action");

    if (cmd) document.execCommand(cmd, false, null);
    if (action === "clearFormat") {
      document.execCommand("removeFormat", false, null);
      document.execCommand("unlink", false, null);
    }
  });

  summaryEditor.addEventListener("input", () => {
    btnCopy.disabled = !summaryEditor.textContent.trim();
  });

  // UPDATED: load the "Transactions" sheet specifically
  fileEl.addEventListener("change", async () => {
    setStatus("", "");
    const f = fileEl.files?.[0];
    if (!f) return;

    try {
      if (!window.XLSX)
        throw new Error("Missing XLSX library (xlsx.full.min.js).");

      fileName = f.name;
      const buf = await f.arrayBuffer();
      const wb = XLSX.read(buf, { type: "array", cellDates: true });

      const sheetName = findSheetByName(wb, "Transactions");
      if (!sheetName) {
        const available = (wb.SheetNames || []).join(", ") || "(none)";
        throw new Error(
          `Sheet "Transactions" not found. Available: ${available}`,
        );
      }

      const ws = wb.Sheets[sheetName];
      const json = XLSX.utils.sheet_to_json(ws, { defval: "" });
      if (!json.length)
        throw new Error('No rows found in "Transactions" sheet.');

      rows = json;

      btnGenerate.disabled = false;
      btnClear.disabled = false;

      setStatus(`Loaded: ${f.name} (Sheet: ${sheetName})`, "ok");
    } catch (err) {
      clearAll();
      setStatus(err?.message || "Failed to load file.", "bad");
    }
  });

  btnGenerate.addEventListener("click", () => {
    try {
      const html = buildSummaryHtml();
      summaryEditor.innerHTML = html;
      btnCopy.disabled = !summaryEditor.textContent.trim();
      setStatus("Generated. Edit the summary as needed.", "ok");
    } catch (err) {
      setStatus(err?.message || "Failed to generate summary.", "bad");
    }
  });

  btnCopy.addEventListener("click", copySummary);
  btnClear.addEventListener("click", clearAll);

  clearAll();
})();
